[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.setup]
nixPkgs = ["python311", "pip", "nodejs_18"]

[phases.install]
cmds = [
    "python3 --version",
    "python3 -m pip --version",
    "cd backend",
    "python3 -m pip install --upgrade pip",
    "python3 -m pip install -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "bash start.sh"

